name: Telegram Uptime Alerts

on:
  schedule:
    - cron: "*/5 * * * *" # каждые 5 минут
  workflow_dispatch:

jobs:
  check-sites:
    name: Check Sites and Notify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y jq

      - name: Get down sites
        id: get-down
        run: |
          if [ -f ".upptime/summary.json" ]; then
            down=$(jq -r '.sites[] | select(.status != "up") | "- \(.name): \(.url)"' .upptime/summary.json | tr '\n' '\n')
            echo "down_sites<<EOF" >> $GITHUB_ENV
            echo "$down" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - name: Send Telegram alert
        if: env.down_sites != ''
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚨 Один или несколько сайтов не работают:
            ${{ env.down_sites }}
            
            📊 Статус: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
